### ISSUE TITLE
Fight doesn't have an event other than combatants

### ISSUE THREAD

**Issue by parouuu** [WoWAnalyzer/WoWAnalyzer#2131]
Got this error while parsing my logs: https://www.warcraftlogs.com/reports/fRFPgAX83zKZQWML#fight=last&type=healing&source=29

Fight doesn't have an event other than combatants, something must have gone wrong.
Error: Fight doesn't have an event other than combatants, something must have gone wrong.
    at t.value (https://wowanalyzer.com/static/js/Monk.1e5e1ff5.chunk.js:1:68909)
    at t.value (https://wowanalyzer.com/static/js/Monk.1e5e1ff5.chunk.js:1:443559)
    at https://wowanalyzer.com/static/js/Monk.1e5e1ff5.chunk.js:1:142898
    at Array.forEach (<anonymous>)
    at t.value (https://wowanalyzer.com/static/js/Monk.1e5e1ff5.chunk.js:1:142860)
    at t.<anonymous> (https://wowanalyzer.com/static/js/main.653d7b6b.js:1:1158992)
    at a (https://wowanalyzer.com/static/js/main.653d7b6b.js:1:554303)
    at Generator._invoke (https://wowanalyzer.com/static/js/main.653d7b6b.js:1:555349)
    at Generator.e.(anonymous function) [as next] (https://wowanalyzer.com/static/js/main.653d7b6b.js:1:554482)
    at a (https://wowanalyzer.com/static/js/main.653d7b6b.js:1:1155105)
    at https://wowanalyzer.com/static/js/main.653d7b6b.js:1:1155199

**Comment by joshinat0r** [comment]
Should work now.
https://wowanalyzer.com/report/fRFPgAX83zKZQWML/35-Normal+Zul+-+Kill+(5:37)/29-Moines

That happens when WCL is sending a corrupted log and it takes some time until our cache-busting is loading it again. Traffic was insane in the last hours, shouldn't happen once WCL is back to stable.
