### ISSUE TITLE
[Marksman] TypeError: t.toFixed is not a function

### ISSUE THREAD

**Issue by Galandel** [WoWAnalyzer/WoWAnalyzer#2378]
TypeError: t.toFixed is not a function
    at https://wowanalyzer.com/static/js/Hunter.6eb97412.chunk.js:1:999128
    at e.value (https://wowanalyzer.com/static/js/Hunter.6eb97412.chunk.js:1:843938)
    at t.value (https://wowanalyzer.com/static/js/Hunter.6eb97412.chunk.js:1:999034)
    at https://wowanalyzer.com/static/js/Hunter.6eb97412.chunk.js:1:133811
    at Array.forEach (<anonymous>)
    at t.value (https://wowanalyzer.com/static/js/Hunter.6eb97412.chunk.js:1:132782)
    at t.value (https://wowanalyzer.com/static/js/main.817e33a0.js:1:1082582)
    at t.value (https://wowanalyzer.com/static/js/main.817e33a0.js:1:1085843)
    at Nn (https://wowanalyzer.com/static/js/main.817e33a0.js:1:393118)
    at kn (https://wowanalyzer.com/static/js/main.817e33a0.js:1:398726)
    at qn (https://wowanalyzer.com/static/js/main.817e33a0.js:1:407475)
    at Zn (https://wowanalyzer.com/static/js/main.817e33a0.js:1:407783)
    at dr (https://wowanalyzer.com/static/js/main.817e33a0.js:1:411167)
    at sr (https://wowanalyzer.com/static/js/main.817e33a0.js:1:410676)
    at lr (https://wowanalyzer.com/static/js/main.817e33a0.js:1:410502)
    at ir (https://wowanalyzer.com/static/js/main.817e33a0.js:1:409874)
    at $n (https://wowanalyzer.com/static/js/main.817e33a0.js:1:409233)
    at Object.enqueueSetState (https://wowanalyzer.com/static/js/main.817e33a0.js:1:441387)
    at t.i.setState (https://wowanalyzer.com/static/js/main.817e33a0.js:1:350778)
    at t.<anonymous> (https://wowanalyzer.com/static/js/main.817e33a0.js:1:1056029)
    at r (https://wowanalyzer.com/static/js/main.817e33a0.js:1:863880)
    at Generator._invoke (https://wowanalyzer.com/static/js/main.817e33a0.js:1:864926)
    at Generator.e.(anonymous function) [as next] (https://wowanalyzer.com/static/js/main.817e33a0.js:1:864059)
    at r (https://wowanalyzer.com/static/js/main.817e33a0.js:1:1052505)
    at https://wowanalyzer.com/static/js/main.817e33a0.js:1:1052599

**Comment by Pewtro** [comment]
PR #2379 fixes this, sorry for the inconvenience.
