### ISSUE TITLE
Even More Info on Cooldown page for Balance druid produces error

### ISSUE THREAD

**Issue by Mrnikbobjeff** [WoWAnalyzer/WoWAnalyzer#3169]
Error occurred here: https://www.wowanalyzer.com/report/mwH9yDnMVhjkpRFf/18-Mythic+Lady+Jaina+Proudmoore+-+Wipe+17+(9:12)/Nusigma/cooldowns
Stack Trace:
TypeError: Cannot read property 'timestamp' of undefined
    at https://www.wowanalyzer.com/static/js/2.9ab68ef6.chunk.js:1:13904
    at Array.map (<anonymous>)
    at t.value (https://www.wowanalyzer.com/static/js/2.9ab68ef6.chunk.js:1:13741)
    at li (https://www.wowanalyzer.com/static/js/81.2b9901ac.chunk.js:1:167501)
    at si (https://www.wowanalyzer.com/static/js/81.2b9901ac.chunk.js:1:167294)
    at hi (https://www.wowanalyzer.com/static/js/81.2b9901ac.chunk.js:1:171451)
    at Ki (https://www.wowanalyzer.com/static/js/81.2b9901ac.chunk.js:1:186442)
    at Gi (https://www.wowanalyzer.com/static/js/81.2b9901ac.chunk.js:1:186819)
    at Ra (https://www.wowanalyzer.com/static/js/81.2b9901ac.chunk.js:1:193311)
    at Na (https://www.wowanalyzer.com/static/js/81.2b9901ac.chunk.js:1:192691)
    at Fa (https://www.wowanalyzer.com/static/js/81.2b9901ac.chunk.js:1:198906)
    at Cn (https://www.wowanalyzer.com/static/js/81.2b9901ac.chunk.js:1:138005)
    at HTMLDocument.o (https://www.wowanalyzer.com/static/js/81.2b9901ac.chunk.js:1:214616)

The above error occurred in the component:
    in t
    in li
    in ul
    in O
    in div
    in div
    in o
    in a
    in div
    in div
    in a
    in Connect(a)
    in a
    in a
    in Connect(a)
    in a
    in a
    in Connect(a)
    in t
    in withRouter(Connect(a))
    in a
    in Connect(a)
    in a
    in Connect(a)
    in a
    in Connect(a)
    in t
    in withRouter(Connect(a))
    in a
    in qn
    in t
    in t
    in div
    in a
    in Connect(a)
    in t
    in withRouter(Connect(a))
    in Unknown
    in t
    in withRouter()
    in t
    in t
    in t
    in a
    in Connect(a)
    in a
    in a
    in a
    in a
    in oi

**Comment by JacobRReed** [comment]
Unable to reproduce this using the link

**Comment by abelito75** [comment]
Everytime I go to the link and follow his steps it crashes for me. I can take a look later today

**Comment by abelito75** [comment]
It appears this is broken for all specs

**Comment by abelito75** [comment]
This has been fixed. Should close the ticket
