### ISSUE TITLE
Loading chunk 27 failed. (error: https://wowanalyzer.com/static/js/FireMage.fc032896.chunk.js)

### ISSUE THREAD

**Issue by luukholleman** [WoWAnalyzer/WoWAnalyzer#4327]
Fire mage analyzer fails loading. It tells me to report here so here I am :)

URL https://wowanalyzer.com/report/Y3GqXNQnAbfVWjKt/7-3+Shriekwing/Skuppy/standard

```
ChunkLoadError: Loading chunk 27 failed.
(error: https://wowanalyzer.com/static/js/FireMage.fc032896.chunk.js)
    at Function.c.e (https://wowanalyzer.com/report/Y3GqXNQnAbfVWjKt/7-3+Shriekwing/Skuppy/standard:1:11343)
    at parser (https://wowanalyzer.com/static/js/main.76d488e3.chunk.js:1:591101)
    at https://wowanalyzer.com/static/js/main.76d488e3.chunk.js:1:272211
    at c (https://wowanalyzer.com/static/js/84.3ee55018.chunk.js:1:232719)
    at Generator._invoke (https://wowanalyzer.com/static/js/84.3ee55018.chunk.js:1:232472)
    at Generator.next (https://wowanalyzer.com/static/js/84.3ee55018.chunk.js:1:233078)
    at r (https://wowanalyzer.com/static/js/84.3ee55018.chunk.js:1:5944)
    at u (https://wowanalyzer.com/static/js/84.3ee55018.chunk.js:1:6147)
    at https://wowanalyzer.com/static/js/84.3ee55018.chunk.js:1:6206
    at new Promise (<anonymous>)
    at https://wowanalyzer.com/static/js/84.3ee55018.chunk.js:1:6087
    at l (https://wowanalyzer.com/static/js/main.76d488e3.chunk.js:1:271949)
    at https://wowanalyzer.com/static/js/main.76d488e3.chunk.js:1:272539
    at c (https://wowanalyzer.com/static/js/84.3ee55018.chunk.js:1:232719)
    at Generator._invoke (https://wowanalyzer.com/static/js/84.3ee55018.chunk.js:1:232472)
    at Generator.next (https://wowanalyzer.com/static/js/84.3ee55018.chunk.js:1:233078)
    at r (https://wowanalyzer.com/static/js/84.3ee55018.chunk.js:1:5944)
    at u (https://wowanalyzer.com/static/js/84.3ee55018.chunk.js:1:6147)
```

**Comment by MartijnHols** [comment]
Thanks for your report, should be fixed now.
