### ISSUE TITLE
Loading Chunk 3 Failed (error: https://wowanalyzer.com/static/js/3.88bff5c5.chunk.js)

### ISSUE THREAD

**Issue by Muroxxas** [WoWAnalyzer/WoWAnalyzer#4342]
Attempting to view data regarding the performance of any hunters on a Heroic Stone Legion Generals kill results in an exception being thrown. Seemingly, this exception is thrown regardless of hunter spec.

`ChunkLoadError: Loading chunk 3 failed.
(error: https://wowanalyzer.com/static/js/3.88bff5c5.chunk.js)
at Function.c.e (https://wowanalyzer.com/:1:11295)
at parser (https://wowanalyzer.com/static/js/main.983fb336.chunk.js:1:571318)
at https://wowanalyzer.com/static/js/main.983fb336.chunk.js:1:272623
at c (https://wowanalyzer.com/static/js/84.d6717ab6.chunk.js:2:232647)
at Generator._invoke (https://wowanalyzer.com/static/js/84.d6717ab6.chunk.js:2:232400)
at Generator.next (https://wowanalyzer.com/static/js/84.d6717ab6.chunk.js:2:233006)
at r (https://wowanalyzer.com/static/js/84.d6717ab6.chunk.js:2:5872)
at u (https://wowanalyzer.com/static/js/84.d6717ab6.chunk.js:2:6075)
at https://wowanalyzer.com/static/js/84.d6717ab6.chunk.js:2:6134
at new Promise (<anonymous>)`

Log used to generate error : https://www.warcraftlogs.com/reports/vT9QPYRKVn6kxHWG/#fight=17

**Comment by DylanDirlam** [comment]
Thanks for the report @Muroxxas. It seems to be an issue with certain ISPs/Cloudflare causing it and there are a handful of other users having the same issue. I would check back in later to see if it's working, that link works fine for me.

**Comment by MartijnHols** [comment]
This should be fixed.
