### ISSUE TITLE
TypeError: Cannot redefine property: values

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#577]
https://sentry.io/wowanalyzer/wowanalyzer/issues/378341971/

```
TypeError: Cannot redefine property: values
  at defineProperty (/)
  at Object.G (/v2/polyfill.min.js:3:3527)
  at hide (../node_modules/core-js/modules/_hide.js:4:1)
  at redefine (../node_modules/core-js/modules/_redefine.js:22:1)
  at $export (../node_modules/core-js/modules/_export.js:27:1)
...
(13 additional frame(s) were not displayed)
```

**Comment by MartijnHols** [comment]
Should be fixed by using a baked in polyfill.
