### ISSUE TITLE
Mage Arcane Error While rendering

### ISSUE THREAD

**Issue by ViniciusTafuri** [WoWAnalyzer/WoWAnalyzer#7066]
This is usually caused by a bug in our code. If you're handy with computers please consider sending us a Pull Request with a fix on [GitHub](https://github.com/WoWAnalyzer/WoWAnalyzer). Otherwise please let us know in an issue on [GitHub](https://github.com/WoWAnalyzer/WoWAnalyzer) or leave us a message on [Discord](https://wowanalyzer.com/discord) so we can fix it for you.

The error
Technical information to help you fix it. Or us if not you. Technical information to help whoever is inclined to fix the issue.

Sentry event ID: 45373e4110fd43d7bd2fc18a3739af68

Cannot read properties of undefined (reading 'borderColor')

TypeError: Cannot read properties of undefined (reading 'borderColor')
    at https://wowanalyzer.com/assets/CombatLogParser-CfpuSIA2.js:1:16730
    at Array.map (<anonymous>)
    at Te.render (https://wowanalyzer.com/assets/CombatLogParser-CfpuSIA2.js:1:16615)
    at Gf (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:43:65371)
    at Rg (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:43:65169)
    at P_ (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:47:9613)
    at C_ (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:47:946)
    at uk (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:47:874)
    at Yo (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:47:728)
    at ad (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:45:10801)
    at https://wowanalyzer.com/assets/index-1Xr_gzdK.js:43:38677
    at e.unstable_runWithPriority (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:32:3836)
    at Nr (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:43:38455)
    at Z1 (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:43:38623)
    at un (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:43:38558)
    at er (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:45:8411)
    at Object.enqueueSetState (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:43:42540)
    at ro.setState (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:18:1371)
    at https://wowanalyzer.com/assets/CombatLogParser-CfpuSIA2.js:1:16140
The above error occurred in the component:
    at Te (https://wowanalyzer.com/assets/CombatLogParser-CfpuSIA2.js:1:15775)
    at div
    at section
    at F (https://wowanalyzer.com/assets/index-BaxUjwxO.js:1:1414)
    at div
    at div
    at https://wowanalyzer.com/assets/index-RvBgng9S.js:7:124469
    at section
    at j (https://wowanalyzer.com/assets/Dropdown-Di4cZip1.js:1:403)
    at b (https://wowanalyzer.com/assets/index-BaxUjwxO.js:1:743)
    at Tt (https://wowanalyzer.com/assets/CombatLogParser-CfpuSIA2.js:1:17204)
    at JEe (https://wowanalyzer.com/assets/CombatLogParser-1EgbRxvs.js:213:48603)
    at Jve (https://wowanalyzer.com/assets/CombatLogParser-1EgbRxvs.js:211:30225)
    at div
    at V (https://wowanalyzer.com/assets/index-BaxUjwxO.js:1:1342)
    at div
    at U (https://wowanalyzer.com/assets/overview-DqQmqUpw.js:1:4471)
    at te (https://wowanalyzer.com/assets/overview-DqQmqUpw.js:1:5374)
    at X2 (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:95:4058)
    at jS (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:95:7035)
    at n (https://wowanalyzer.com/assets/CombatLogParserContext-CMrk8BDO.js:1:93)
    at div
    at _i (https://wowanalyzer.com/assets/index-B9-8WULM.js:1:62875)
    at Ii (https://wowanalyzer.com/assets/index-B9-8WULM.js:1:71945)
    at yi (https://wowanalyzer.com/assets/index-B9-8WULM.js:1:71185)
    at w (https://wowanalyzer.com/assets/ConfigContext-Ba5n6unz.js:1:342)
    at $n (https://wowanalyzer.com/assets/index-B9-8WULM.js:1:41239)
    at a (https://wowanalyzer.com/assets/FightContext-BEsg9NgN.js:1:182)
    at nn (https://wowanalyzer.com/assets/index-B9-8WULM.js:1:9215)
    at ze (https://wowanalyzer.com/assets/index-B9-8WULM.js:1:19542)
    at Ln (https://wowanalyzer.com/assets/index-B9-8WULM.js:1:21294)
    at ld (https://wowanalyzer.com/assets/emotion-styled-base.browser.esm-C0WxT1XK.js:1:318875)
    at Bs (https://wowanalyzer.com/assets/emotion-styled-base.browser.esm-C0WxT1XK.js:1:319015)
    at Gs (https://wowanalyzer.com/assets/emotion-styled-base.browser.esm-C0WxT1XK.js:1:318687)
    at Zn (https://wowanalyzer.com/assets/index-B9-8WULM.js:1:45603)
    at fS (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:76:3642)
    at wb (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:135:32805)
    at gr
    at X2 (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:95:4058)
    at jS (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:95:7035)
    at div
    at SM (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:135:29404)
    at X2 (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:95:4058)
    at Y2 (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:95:3298)
    at w4 (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:104:5002)
    at r4 (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:95:7093)
    at _4 (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:104:2320)
    at X6
    at fS (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:76:3642)
    at wb (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:135:32805)
    at qb (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:141:223)
    at KN (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:104:23145)
    at WL (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:141:17621)
    at RD (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:133:475)
    at za (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:141:11684)
    at VL (https://wowanalyzer.com/assets/index-1Xr_gzdK.js:141:17904)

**Comment by ViniciusTafuri** [comment]
More info:

ManaLevelGraph.jsx

Line: 83
series = {name: 'Demolishing Terror', id: 272, guid: 137626, type: 'Boss', data: Array(93), …}

ManaStyles['Boss-6'].BorderColor

![image](https://github.com/user-attachments/assets/22f3eec4-f11b-468c-b1ce-1e2422d23b72)

Probably some Siege of Boralus Boss/Mob without said border.

**Comment by WydD** [comment]
I have got a similar issue on [this report](https://wowanalyzer.com/report/VCYyvWzfDMrqPmg9/2-Mythic++Mists+of+Tirna+Scithe+-+Kill+(27:36)/Fururf/standard)

It crashes on this line but this time it says `TypeError: Pe[("Boss-" + (intermediate value))] is undefined`

**Comment by buchirradu** [comment]
It seems this issue is caused because for Mists of Tirna Scithe WCL api return too many bosses for `ManaStyles` to process:
 - 'Ingra Maloch'
 - 'Gormling Larva'
 - 'Illusionary Vulpin'
 - "Tred'ova"
 - 'Illusionary Clone'
 - 'Droman Oulfarran'
 - 'Mistcaller'
`ManaStyles` support 5 styles of format ManaStyles[`Boss-${i}`], while as you can see above 6 are needed.

Now a quick fix can be to extend the styles, but then the graph looks wrong 
![image](https://github.com/user-attachments/assets/5c879417-77fa-48ea-a7a3-aca3a33b2fd0)

The root cause it boss spawns also have a boss tag and they should be blacklisted somehow. 
I don't know if other dungeons can trigger this scenario
