### ISSUE TITLE
Arcane Mage Analysis Breaking

### ISSUE THREAD

**Issue by Acratin** [WoWAnalyzer/WoWAnalyzer#7090]
Getting this basic type of bug with every attempt to use on Arcane Mage

Sentry event ID: 85b4e690a2954b459569777504cd2abf

Cannot read properties of undefined (reading 'borderColor')

TypeError: Cannot read properties of undefined (reading 'borderColor')
    at https://wowanalyzer.com/assets/CombatLogParser-kJiKV-As.js:1:16683
    at Array.map (<anonymous>)
    at Te.render (https://wowanalyzer.com/assets/CombatLogParser-kJiKV-As.js:1:16568)
    at Gf (https://wowanalyzer.com/assets/index-1xYkTXSt.js:43:65371)
    at Rg (https://wowanalyzer.com/assets/index-1xYkTXSt.js:43:65169)
    at P_ (https://wowanalyzer.com/assets/index-1xYkTXSt.js:47:9613)
    at C_ (https://wowanalyzer.com/assets/index-1xYkTXSt.js:47:946)
    at uk (https://wowanalyzer.com/assets/index-1xYkTXSt.js:47:874)
    at Yo (https://wowanalyzer.com/assets/index-1xYkTXSt.js:47:728)
    at ad (https://wowanalyzer.com/assets/index-1xYkTXSt.js:45:10801)
    at https://wowanalyzer.com/assets/index-1xYkTXSt.js:43:38677
    at e.unstable_runWithPriority (https://wowanalyzer.com/assets/index-1xYkTXSt.js:32:3836)
    at Nr (https://wowanalyzer.com/assets/index-1xYkTXSt.js:43:38455)
    at Z1 (https://wowanalyzer.com/assets/index-1xYkTXSt.js:43:38623)
    at un (https://wowanalyzer.com/assets/index-1xYkTXSt.js:43:38558)
    at er (https://wowanalyzer.com/assets/index-1xYkTXSt.js:45:8411)
    at Object.enqueueSetState (https://wowanalyzer.com/assets/index-1xYkTXSt.js:43:42540)
    at ro.setState (https://wowanalyzer.com/assets/index-1xYkTXSt.js:18:1371)
    at https://wowanalyzer.com/assets/CombatLogParser-kJiKV-As.js:1:16093
The above error occurred in the component:
    at Te (https://wowanalyzer.com/assets/CombatLogParser-kJiKV-As.js:1:15728)
    at div
    at section
    at A (https://wowanalyzer.com/assets/index-C5H9HjXB.js:1:1414)
    at div
    at div
    at https://wowanalyzer.com/assets/index-Cc043pRn.js:7:135933
    at section
    at j (https://wowanalyzer.com/assets/Dropdown-CBG_FPXc.js:1:403)
    at v (https://wowanalyzer.com/assets/index-C5H9HjXB.js:1:743)
    at Tt (https://wowanalyzer.com/assets/CombatLogParser-kJiKV-As.js:1:17157)
    at JEe (https://wowanalyzer.com/assets/CombatLogParser-CeUuCyPF.js:213:48065)
    at Jve (https://wowanalyzer.com/assets/CombatLogParser-CeUuCyPF.js:211:30225)
    at div
    at V (https://wowanalyzer.com/assets/index-C5H9HjXB.js:1:1342)
    at div
    at U (https://wowanalyzer.com/assets/overview-ClA8vAao.js:1:4471)
    at te (https://wowanalyzer.com/assets/overview-ClA8vAao.js:1:5374)
    at X4 (https://wowanalyzer.com/assets/index-1xYkTXSt.js:95:4058)
    at jS (https://wowanalyzer.com/assets/index-1xYkTXSt.js:95:7035)
    at n (https://wowanalyzer.com/assets/CombatLogParserContext-BNYfAQEF.js:1:93)
    at div
    at _i (https://wowanalyzer.com/assets/index-IeRoALHg.js:1:62875)
    at Ii (https://wowanalyzer.com/assets/index-IeRoALHg.js:1:71945)
    at yi (https://wowanalyzer.com/assets/index-IeRoALHg.js:1:71185)
    at w (https://wowanalyzer.com/assets/ConfigContext-CHDNBiw4.js:1:342)
    at $n (https://wowanalyzer.com/assets/index-IeRoALHg.js:1:41239)
    at a (https://wowanalyzer.com/assets/FightContext-DX6VgFKx.js:1:182)
    at nn (https://wowanalyzer.com/assets/index-IeRoALHg.js:1:9215)
    at ze (https://wowanalyzer.com/assets/index-IeRoALHg.js:1:19542)
    at Ln (https://wowanalyzer.com/assets/index-IeRoALHg.js:1:21294)
    at ld (https://wowanalyzer.com/assets/emotion-styled-base.browser.esm-BBKpSl_3.js:1:319501)
    at Bs (https://wowanalyzer.com/assets/emotion-styled-base.browser.esm-BBKpSl_3.js:1:319641)
    at Gs (https://wowanalyzer.com/assets/emotion-styled-base.browser.esm-BBKpSl_3.js:1:319313)
    at Zn (https://wowanalyzer.com/assets/index-IeRoALHg.js:1:45603)
    at fS (https://wowanalyzer.com/assets/index-1xYkTXSt.js:76:3642)
    at wb (https://wowanalyzer.com/assets/index-1xYkTXSt.js:135:32805)
    at gr
    at X4 (https://wowanalyzer.com/assets/index-1xYkTXSt.js:95:4058)
    at jS (https://wowanalyzer.com/assets/index-1xYkTXSt.js:95:7035)
    at div
    at SM (https://wowanalyzer.com/assets/index-1xYkTXSt.js:135:29404)
    at X4 (https://wowanalyzer.com/assets/index-1xYkTXSt.js:95:4058)
    at Y4 (https://wowanalyzer.com/assets/index-1xYkTXSt.js:95:3298)
    at w2 (https://wowanalyzer.com/assets/index-1xYkTXSt.js:104:5002)
    at r2 (https://wowanalyzer.com/assets/index-1xYkTXSt.js:95:7093)
    at _2 (https://wowanalyzer.com/assets/index-1xYkTXSt.js:104:2320)
    at X6
    at fS (https://wowanalyzer.com/assets/index-1xYkTXSt.js:76:3642)
    at wb (https://wowanalyzer.com/assets/index-1xYkTXSt.js:135:32805)
    at qb (https://wowanalyzer.com/assets/index-1xYkTXSt.js:141:223)
    at KN (https://wowanalyzer.com/assets/index-1xYkTXSt.js:104:23145)
    at WL (https://wowanalyzer.com/assets/index-1xYkTXSt.js:141:17621)
    at R5 (https://wowanalyzer.com/assets/index-1xYkTXSt.js:133:475)
    at za (https://wowanalyzer.com/assets/index-1xYkTXSt.js:141:11684)
    at VL (https://wowanalyzer.com/assets/index-1xYkTXSt.js:141:17904)

**Comment by Sharrq** [comment]
Can you please include a link to the log and which flight/pull it is so we can investigate further?

**Comment by Acratin** [comment]
Certainly!

https://www.warcraftlogs.com/reports/aqZ3P9g7LQ1wXWpC#fight=last&type=damage-done
is the log in question at the moment, but if you look at my warcraft logs
account it's giving this bug for every single time I attempt to analyze
Merini - Arcane Mage.

**Comment by Acratin** [comment]
To note: It's happening on both logs in this file. 

I did just check this raid one and it appears to be cooperating here: https://www.warcraftlogs.com/reports/kZtMLKBXJjPGdzfF#fight=5&type=damage-done

**Comment by Sharrq** [comment]
Thanks, I believe this is the mana graph that is erroring. I'll look into it a bit further though and see if I can narrow it down

**Comment by buchirradu** [comment]
Can this be a duplicate of https://github.com/WoWAnalyzer/WoWAnalyzer/issues/7066 ?

**Comment by Acratin** [comment]
It looks to be, Buchirradu

**Comment by CericME** [comment]
This one also looks to be closeable from the PR.
