### ISSUE TITLE
Marksmanship Hunter: crash

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#852]
https://wowanalyzer.com/report/J16tnGg4H9VdXL7K/16-LFR+Chronomatic+Anomaly+-+Kill+(1:38)/Ftaack
https://sentry.io/share/issue/d1bab9a4f7bf405d97d8111321d45a31/

```
TypeError: Cannot set property 'end' of undefined
  at apply (Parser/Hunter/Marksmanship/Modules/Talents/PatientSniper/PatientSniperTracker.js:210:16)
  at apply (Parser/Core/Analyzer.js:29:7)
  at apply (Parser/Core/Analyzer.js:11:7)
  at None (Parser/Core/CombatLogParser.js:370:11)
  at Array.forEach (<anonymous>)
...
(10 additional frame(s) were not displayed)
```

**Comment by Pewtro** [comment]
Fixed in #856
